# spring.main.web-application-type=none

# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
spring:
  main:
    banner-mode: off
  ai:
    mcp:
      server:
        name: my-mcp-server
        version: 0.0.1
        stdio: true

# logging:
#   pattern:
#     console:

logging:
  file:
    name: ./model-context-protocol/weather/starter-webmvc-server/target/starter-webmvc-server.log
